"""empty message

Revision ID: 1466d8a75810
Revises: d05d206a21e5
Create Date: 2023-08-28 10:48:34.021781

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1466d8a75810'
down_revision = 'd05d206a21e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hasVoted', sa.Boolean(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Users')
    # ### end Alembic commands ###
