"""empty message

Revision ID: d05d206a21e5
Revises: 
Create Date: 2023-08-28 10:46:42.177045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd05d206a21e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Candidates')
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('hasVoted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('password', sa.String(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('Password')
        batch_op.drop_column('E-mail')
        batch_op.drop_column('Has voted')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Has voted', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('E-mail', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('Password', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('password')
        batch_op.drop_column('hasVoted')
        batch_op.drop_column('email')

    op.create_table('Candidates',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('Name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Votes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Candidates_pkey')
    )
    # ### end Alembic commands ###
